<?php

include_once('kendra_upload.features.inc');

function kendra_upload_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	switch ($op) {
		case 'insert':
			// only create triples on insert
			// TODO: handle update event
			//case 'update':
			if ($node->type == 'kendra_import') {
				if (module_exists('krumo')
				&& 	(($handle = fopen($node->field_upload_file[0]['filepath'], 'r')) !== FALSE)
				) {
					// debug: process immediately
					_kendra_upload_process_csv($node->nid);
				} else {
					job_queue_add('_kendra_upload_process_csv',
	          "Process the uploaded file for node {$node->nid}",
					array($node->nid),
	          '', TRUE);
				}
			}
			if ($node->type == 'kendra_format') {
				_kendra_upload_process_format($node->nid);
			}
			break;
		case 'view':
			if ($node->type == 'kendra_import') {
				$graph = url("node/{$node->nid}", array('absolute' => TRUE));
				$result = kendra_rdf_send("SELECT * FROM <{$graph}> WHERE {?s ?p ?o}");
				$node->content['sparql_result'] = array(
          '#value' => $result->data,
				);
				$node->content['atom_feed'] = array(
			    '#value' => l('<strong>Atom Feed</strong>'. theme('image', 'misc/feed.png'), "node/{$node->nid}/atom", array('html' => TRUE)),
          '#weight' => -10,
				);
			}
			if ($node->type == 'kendra_format') {
				$graph = url("node/{$node->nid}", array('absolute' => TRUE));
				$result = kendra_rdf_send("SELECT * FROM <{$graph}> WHERE {?s ?p ?o}");
				$node->content['sparql_result'] = array(
          '#value' => $result->data,
          '#weight' => 99,
				);
			}
			break;
	}
}

function array_trim(&$value, $key) {
	$value = trim($value);
}

function _kendra_upload_process_format($nid) {
	$node = node_load($nid);
	$graph = url("node/{$nid}", array('absolute' => TRUE));
	$query = "";
	$triples = "";
	foreach ($node->field_format_prop as $key => $prop) {
		$row_uri = $graph ."/property#{$key}";
		$relation = $prop['value']; // TODO: filter user input
		$triples .= "\n<{$row_uri}> <{$relation}> \"\" .\n";
	}
	watchdog('kendra_format', "triples: \n\n". $triples ."\n\n from \n\n". print_r($node, TRUE));
	if (!empty($triples)) {
		job_queue_add('kendra_rdf_insert', "insert for graph {$graph}", array($graph, $triples), '', TRUE);
	}
}

function _kendra_upload_process_csv($nid) {
	$node = node_load($nid);

	if (($handle = fopen($node->field_upload_file[0]['filepath'], 'r')) !== FALSE) {
		$headers = fgetcsv($handle, 1000, ',', '"');

		// remove whitespace from column headers
		array_walk($headers, 'array_trim');

		$row = 1;
		$triple_no = 0;

		$graph = url("node/{$nid}", array('absolute' => TRUE));
		$query = "";
		$triples = array();
		$triples[$triple_no] = "";

		while (($data = fgetcsv($handle, 1000, ',', '"')) !== FALSE) {
			foreach ($data as $key => $value) {
				if (!empty($value)) {
					/**
					 * build the SPARQL query
					 * note: value is encoded as a string
					 */
					$row_uri = sprintf("%s/rows#%s", $graph, $row);
					$relation = sprintf("%s/relation#%s", $graph, urlencode($headers[$key]));
					$triples[$triple_no] .= sprintf("\n<%s> <%s> \"%s\".", $row_uri, $relation, addslashes($value));

					if (mb_strlen($triples[$triple_no]) > SPARQL_TRIPLE_LIMIT) {
						$triple_no++;
					}
				}
			}

			// creation of cat nodes for solr testing
			$data['source_nid'] = $nid;
			$data['source_row'] = $row;
			_kendra_uploads_add_cat_node($headers, $data);

			$row++;
		}

		if (!empty($triples)) {
			/**
			 * empty out any existing RDF graph prior to insertion of the new triples
			 */
			//$response = kendra_rdf_send("DROP GRAPH <{$graph}> ");
			$response = kendra_rdf_send("CLEAR GRAPH <{$graph}> ");
			$response = kendra_rdf_send("CREATE GRAPH <{$graph}> ");

			foreach ($triples as $triple_s) {
				job_queue_add('kendra_rdf_insert', "insert for graph {$graph}", array($graph, $triple_s), '', TRUE);
			}
		}
	}
	fclose($handle);
}

function _kendra_uploads_add_cat_node($headers, $data) {
	// Check for kendra_cat module, and if it exists pass the data
	// for creation of kendra catalogue node. This is only to be
	// used during testing of apachesolr module.
	if (function_exists('kendra_cat_add_node')) {
		kendra_cat_add_node($headers, $data);
	} else {
		// kendra_cat module not enabled, do nothing.
	}
}

