<?php

define('SPARQL_TRIPLE_LIMIT', 4000);

/**
 * Implementation of hook_ctools_plugin_api().
 */
function kendra_upload_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "feeds" && $api == "feeds_importer_default") {
    return array("version" => 1);
  }
  elseif ($module == "strongarm" && $api == "strongarm") {
    return array("version" => 1);
  }
}

/**
 * Implementation of hook_node_info().
 */
function kendra_upload_node_info() {
  $items = array(
    'kendra_format' => array(
      'name' => t('Kendra Format'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '0',
      'body_label' => '',
      'min_word_count' => '0',
      'help' => '',
    ),
    'kendra_import' => array(
      'name' => t('Kendra Import'),
      'module' => 'features',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'has_body' => '0',
      'body_label' => '',
      'min_word_count' => '0',
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implementation of hook_views_api().
 */
function kendra_upload_views_api() {
  return array(
    'api' => '2',
  );
}
