<?php

/**
 * Implementation of hook_content_default_fields().
 */
function kendra_upload_content_default_fields() {
  $fields = array();

  // Exported field: field_upload_file
  $fields['kendra_import-field_upload_file'] = array(
    'field_name' => 'field_upload_file',
    'type_name' => 'kendra_import',
    'display_settings' => array(
      'label' => array(
        'format' => 'above',
        'exclude' => 0,
      ),
      'teaser' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      'full' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
      '4' => array(
        'format' => 'default',
        'exclude' => 0,
      ),
    ),
    'widget_active' => '1',
    'type' => 'filefield',
    'required' => '1',
    'multiple' => '0',
    'module' => 'filefield',
    'active' => '1',
    'list_field' => '0',
    'list_default' => 1,
    'description_field' => '0',
    'widget' => array(
      'file_extensions' => 'csv',
      'file_path' => 'csv_uploads',
      'progress_indicator' => 'bar',
      'max_filesize_per_file' => '',
      'max_filesize_per_node' => '',
      'label' => 'File',
      'weight' => '-4',
      'description' => 'Attach a csv to this upload node.',
      'type' => 'filefield_widget',
      'module' => 'filefield',
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('File');

  return $fields;
}
