<?php

include_once('kendra_cat.features.inc');

function kendra_cat_add_node($headers, $data) {
  // Default node -> csv heading mappings
  $mappings = array(
    'title' => array('Track', 'Title', 'Name'),
    'field_cat_artist' => array('Artist'),
    'field_cat_label' => array('Label'),
    'field_cat_no' => array('Catalogue Number', 'CAE Number'),
    'field_cat_date' => array('Release Date', 'Year'),
    'field_cat_album' => array('Album/ep title', 'Album', 'Album'),
    'field_cat_publisher' => array('Publisher'),
    'field_cat_isrc' => array('ISRC Code'),
  );
  
  // drupal_set_message(print_r($data, TRUE));
  global $user;
  $node = new stdClass();
  $node->uid = $user->uid;
  $node->type = 'kendra_cat';

  foreach ($mappings as $mapping) {
    // default field value
    // foreach mapping
      // check each possible header 
      // assign data if matches
  }

  $node->title                           = $data[2];
  $node->field_cat_artist[0]['value']    = $data[3];
  $node->field_cat_label[0]['value']     = $data[0];
  $node->field_cat_no[0]['value']        = $data[1];
  $node->field_cat_date[0]['value']      = $data[6];
  $node->field_cat_album[0]['value']     = $data[5];
  $node->field_cat_publisher[0]['value'] = $data[8];
  $node->field_cat_isrc[0]['value']      = $data[7];
  node_save($node);  
}

